#cloud-config

coreos:
  units:
    - name: "docker.service"
      drop-ins:
        - name: "50-insecure-registry.conf"
          content: |
            [Service]
            Environment=DOCKER_OPTS='--insecure-registry="localhost:5000'

    - name: "swarm.service"
      enable: true
      command: start
      content: |
        [Unit]
        Description="Swarm initialisation"
        After=docker.service
        Requires=docker.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/sh /home/core/swarm-init.sh

        [Install]
        WantedBy=multi-user.target

write_files:
  - path: /home/core/swarm-init.sh
    permissions: "0755"
    owner: "core"
    content: |
      #!/bin/sh

      touch /home/core/the-script-has-run

      ACCESS_TOKEN=$(wget -qO - --header 'Metadata-Flavor: Google' 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token' | jq -r '.access_token')

      JOIN_TOKEN=$(wget -qO - --header "Authorization: Bearer $ACCESS_TOKEN" 'https://www.googleapis.com/download/storage/v1/b/${BUCKET_NAME}/o/manager-token?alt=media')
      MANAGER_IPS=$(wget -qO - --header "Authorization: Bearer $ACCESS_TOKEN" 'https://www.googleapis.com/storage/v1/b/${BUCKET_NAME}/o?prefix=manager-ips/' | jq -r '.items[].name' | grep -o '[0-9.]*')

      MY_IP=$(wget -qO - --header 'Metadata-Flavor: Google' 'http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ip')

      echo "Adding $MY_IP into the managers list"
      wget -q \
        --header "Authorization: Bearer $ACCESS_TOKEN" \
        --header 'Content-Type: binary/octet-stream' \
        --header 'Content-Length: 0' \
        --post-data '' \
        "https://www.googleapis.com/upload/storage/v1/b/${BUCKET_NAME}/o?uploadType=media&name=manager-ips/$MY_IP"

      for IP in $MANAGER_IPS; do
        echo "Trying to join a swarm managed by $IP..."
        if wget -q --spider -t 1 --connect-timeout 3 $IP:2377; then
          docker swarm join --token $JOIN_TOKEN $IP:2377
          break
        fi
        echo "...Timeout"
      done
