services:
  visualizer:
    deploy:
      placement:
        constraints:
        - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      PORT: 3000
    image: charypar/swarm-dashboard:latest
    ports:
    - 8000:3000/tcp
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '3.1'

