version: "3.1"

services:
  web:
    image: registry:5000/web
    build: web
    ports:
      - 80:3000
    networks:
      - default
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  proxy:
    image: registry:5000/proxy
    build: proxy
    ports:
      - 81:8080
    networks:
      - default
      - private
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  api:
    image: registry:5000/api
    build: api
    networks:
      - private
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    secrets:
      - my_secret
secrets:
  my_secret:
    external: true
networks:
  private:
    ipam:
      driver: default
      config:
        - subnet: 192.168.31.0/24
