version: "3.1"

services:
  rproxy:
    image: localhost:5000/services_rproxy
    build:
      context: rproxy
      args:
        - "config=services"
    environment:
      PORT: 3000
      WEB_HOST: web:3000
      VISUALIZER_HOST: visualizer:3000
    ports:
      - 8080:3000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /var/lib/registry:/var/lib/registry
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  visualizer:
    image: charypar/swarm-dashboard:latest
    environment:
      PORT: 3000
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager
