version: "3.1"

services:
  rproxy:
    image: registry:5000/app_rproxy
    build:
      context: rproxy
      args:
        - "config=app"
    ports:
      - 80:3000
    environment:
      PORT: 3000
      WEB_HOST: web:3000
      API_HOST: gateway:3000
    networks:
      - dmz
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  web:
    image: registry:5000/web
    build: web
    environment:
      PORT: 3000
      API_HOST: gateway:3000
    networks:
      - dmz
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  gateway:
    image: registry:5000/proxy
    build: proxy
    environment:
      PORT: 3000
      API_HOST: api:3000
    networks:
      - dmz
      - private
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  api:
    image: registry:5000/api
    build: api
    environment:
      PORT: 3000
    networks:
      - private
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    secrets:
      - my_secret
secrets:
  my_secret:
    external: true
networks:
  dmz:
    ipam:
      driver: default
      config:
        - subnet: 192.168.31.0/24
  private:
    ipam:
      driver: default
      config:
        - subnet: 192.168.32.0/24
