version: "3.1"

services:
  visualizer:
    image: charypar/swarm-dashboard:latest
    environment:
      PORT: 3000
    ports:
      - 8080:3000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
