version: "3.1"

services:
  load_balancer:
    image: haproxy:1.7.8-alpine
    ports:
      - 80:80
    networks:
      - load_balancer
    extra_hosts:
      - "mgr1:${mgr1}"
      - "wkr1:${wkr1}"
      - "wkr2:${wkr2}"
      - "wkr3:${wkr3}"
    volumes:
      - /tmp/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
networks:
  load_balancer:
