version: "3.1"

services:
  load_balancer:
    image: nginx
    ports:
      - 80:80
    networks:
      - load_balancer
    extra_hosts:
      - "mgr1:${mgr1}"
      - "wkr1:${wkr1}"
      - "wkr2:${wkr2}"
      - "wkr3:${wkr3}"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  load_balancer:
