env:
  registry: eu.gcr.io/microplatform-demo

steps:

  - label: ":docker: Build"
    command: bash .buildkite/steps/build.sh

  - label: ":node: 'configure' utility: unit tests"
    command: cd ./configure && docker build .

  - wait:
