apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    component: web
  ports:
  - port: 3000
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: web
  labels:
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: web
        image: docker.for.mac.localhost:5000/web:71059d2ab2.5
        env:
        - name: API_HOST
          value: gateway:3000
        - name: PORT
          value: "3000"
        ports:
        - name: main-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /_health
            port: main-port
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /_health
            port: main-port
          initialDelaySeconds: 3
          periodSeconds: 3
